In [90]:
import pandas as pd

In [91]:
df=pd.read_csv('stackoverflow/survey_results_public.csv',index_col='Respondent')
df.head(5)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

In [92]:
schema_df=pd.read_csv('stackoverflow/survey_results_schema.csv',index_col='Column')
schema_df.head(5)

                                                 QuestionText
Column
Respondent  Randomized respondent ID number (not in order ...
MainBranch  Which of the following options best describes ...
Hobbyist                              Do you code as a hobby?
Age         What is your age (in years)? If you prefer not...
Age1stCode  At what age did you write your first line of c...

In [93]:
#change ConvertedComp to SalaryByUSD
df.rename(columns = {'ConvertedComp':'SalaryByUSD'},inplace=True)
df['SalaryByUSD']

Respondent
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
         ..
64858   NaN
64867   NaN
64898   NaN
64925   NaN
65112   NaN
Name: SalaryByUSD, Length: 64461, dtype: float64

In [94]:
#change ConvertedComp to SalaryByUSD in schema file
schema_df.rename(index = {'ConvertedComp':'SalaryByUSD'},inplace = True)
schema_df.loc['SalaryByUSD']

QuestionText    Salary converted to annual USD salaries using ...
Name: SalaryByUSD, dtype: object

In [95]:
#change data of two cells
df.loc[[1,2],'SalaryByUSD']='NA'

In [96]:
#change the values of many columns for one row
# here we will change the value of age and CompTotal for the first row
df.loc[1,['Age','CompTotal']]=['NA','NA']
df.head(1)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,SalaryByUSD,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NA,13,Monthly,NA,NA,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27

In [97]:
#edit data using filter
# edit the data where the column values equal to 'Syrian Arab Republic'
#replace it with 'Syria'
my_filter = (df["Country"] == 'Syrian Arab Republic')
df.loc[my_filter,'Country']='Syria'
my_filter = (df["Country"] == 'Syria')
df.loc[my_filter].head(2)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,SalaryByUSD,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
868,"I am not primarily a developer, but I write co...",No,25.0,15,Monthly,100000.0,2328.0,Syria,Syrian pound,SYP,...,Easy,Appropriate in length,No,"Information systems, information technology, o...",ASP.NET Core,NaN,Just as welcome now as I felt last year,44.0,4,2
12250,I am a developer by profession,Yes,21.0,12,Monthly,125000.0,2916.0,Syria,Syrian pound,SYP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Vue.js,jQuery;Laravel,Somewhat more welcome now than last year,7.0,6,2

In [98]:
#Change the CurrencySymbol to lowercase
df['CurrencySymbol']=df['CurrencySymbol'].apply(lambda x:str(x).upper())
df['CurrencySymbol']

Respondent
1        EUR
2        GBP
3        NAN
4        ALL
5        NAN
        ...
64858    NAN
64867    NAN
64898    NAN
64925    NAN
65112    NAN
Name: CurrencySymbol, Length: 64461, dtype: object

In [99]:
# Change the CurrencySymbol to uppercase
df['CurrencySymbol'] = df['CurrencySymbol'].str.upper()
df['CurrencySymbol']

Respondent
1        EUR
2        GBP
3        NAN
4        ALL
5        NAN
        ...
64858    NAN
64867    NAN
64898    NAN
64925    NAN
65112    NAN
Name: CurrencySymbol, Length: 64461, dtype: object

In [108]:
# using applymap() with dataframe, and changing all the data to lowercase.
df.applymap(lambda x:str(x).lower())

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,SalaryByUSD,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1,i am a developer by profession,yes,na,13,monthly,na,na,germany,european euro,eur,...,neither easy nor difficult,appropriate in length,no,"computer science, computer engineering, or sof...",asp.net core,asp.net;asp.net core,just as welcome now as i felt last year,50.0,36,27
2,i am a developer by profession,no,nan,19,nan,nan,na,united kingdom,pound sterling,gbp,...,nan,nan,nan,"computer science, computer engineering, or sof...",nan,nan,somewhat more welcome now than last year,nan,7,4
3,i code primarily as a hobby,yes,nan,15,nan,nan,nan,russian federation,nan,nan,...,neither easy nor difficult,appropriate in length,nan,nan,nan,nan,somewhat more welcome now than last year,nan,4,nan
4,i am a developer by profession,yes,25.0,18,nan,nan,nan,albania,albanian lek,all,...,nan,nan,no,"computer science, computer engineering, or sof...",nan,nan,somewhat less welcome now than last year,40.0,7,4
5,"i used to be a developer by profession, but no...",yes,31.0,16,nan,nan,nan,united states,nan,nan,...,easy,too short,no,"computer science, computer engineering, or sof...",django;ruby on rails,ruby on rails,just as welcome now as i felt last year,nan,15,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64858,nan,yes,nan,16,nan,nan,nan,united states,nan,nan,...,nan,nan,nan,"computer science, computer engineering, or sof...",nan,nan,nan,nan,10,less than 1 year
64867,nan,yes,nan,nan,nan,nan,nan,morocco,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
64898,nan,yes,nan,nan,nan,nan,nan,viet nam,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
64925,nan,yes,nan,nan,nan,nan,nan,poland,nan,nan,...,nan,nan,nan,nan,angular;angular.js;react.js,nan,nan,nan,nan,nan
65112,nan,yes,nan,nan,nan,nan,nan,spain,nan,nan,...,nan,nan,nan,"computer science, computer engineering, or sof...",asp.net core;jquery,angular;angular.js;asp.net core;jquery,nan,nan,nan,nan

In [109]:
df

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,SalaryByUSD,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NA,13,Monthly,NA,NA,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NA,United Kingdom,Pound sterling,GBP,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NAN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NAN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NAN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NAN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NAN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NAN,...,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NAN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [111]:
# using map() with series object
# change value of 'Hobbyist' -----  yes => True, no => False
# we cannot user inplace with map
# so to store the result we assign it
# df['Hobbyist'] = df['Hobbyist'].map({'Yes':'True','No':'False'})
df['Hobbyist'].map({'Yes':'True','No':'False'})

Respondent
1         True
2        False
3         True
4         True
5         True
         ...
64858     True
64867     True
64898     True
64925     True
65112     True
Name: Hobbyist, Length: 64461, dtype: object

In [149]:
#merging two column
df['MajorAndUsedLanguages'] = df['MainBranch'] + '\\' + df['WebframeWorkedWith']
df.head(2)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,SalaryByUSD,Country,CurrencyDesc,CurrencySymbol,...,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro,major and used languages,MajorAndUsedLanguages
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NA,13,Monthly,NA,NA,Germany,European Euro,EUR,...,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27,I am a developer by profession\ASP.NET;ASP.NET...,I am a developer by profession\ASP.NET;ASP.NET...
2,I am a developer by profession,No,NaN,19,NaN,NaN,NA,United Kingdom,Pound sterling,GBP,...,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4,NaN,NaN

In [154]:
# Delete column
df.drop(columns='MajorAndUsedLanguages',inplace = True)

In [155]:
df.head(2)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,SalaryByUSD,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NA,13,Monthly,NA,NA,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NA,United Kingdom,Pound sterling,GBP,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4

In [158]:
#imporve the data of WebframeWorkedWith data
df['WebframeWorkedWith'] = df['WebframeWorkedWith'].str.replace(';',', ')
df['WebframeWorkedWith']

Respondent
1                            ASP.NET, ASP.NET Core
2                                              NaN
3                                              NaN
4                                              NaN
5                                    Ruby on Rails
                           ...
64858                                          NaN
64867                                          NaN
64898                                          NaN
64925                                          NaN
65112    Angular, Angular.js, ASP.NET Core, jQuery
Name: WebframeWorkedWith, Length: 64461, dtype: object

In [159]:
#merging two DataFrames
df.append(schema_df)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,SalaryByUSD,Country,CurrencyDesc,CurrencySymbol,...,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro,QuestionText
1,I am a developer by profession,Yes,NA,13,Monthly,NA,NA,Germany,European Euro,EUR,...,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,"ASP.NET, ASP.NET Core",Just as welcome now as I felt last year,50.0,36,27,NaN
2,I am a developer by profession,No,NaN,19,NaN,NaN,NA,United Kingdom,Pound sterling,GBP,...,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4,NaN
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NAN,...,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,...,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4,NaN
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NAN,...,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WebframeWorkedWith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Which web frameworks have you done extensive d...
WelcomeChange,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Compared to last year, how welcome do you feel..."
WorkWeekHrs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"On average, how many hours per week do you wor..."
YearsCode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Including any education, how many years have y..."
YearsCodePro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"NOT including education, how many years have y..."